# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci 
	firstNum = 1
	secondNum = 1
	thirdNum = 0
	total = 0

	while secondNum  < 4000000 
		thirdNum = firstNum + secondNum
	 	firstNum = secondNum
		secondNum = thirdNum

		if thirdNum % 2 == 0
			total += thirdNum
		end
	end

	puts 'The total of all even fibonacci numbers less than 4 Million is ' + total.to_s
end

fibonacci